name: Hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Hello World ActionSmart334455
        uses: Praveen-1992/hello-world-action@v8
        with:
          who-to-greet: 'GitHub'
